apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\Users\Han\AppData\Local\Microsoft\WinGet\Links\kompose.exe convert -f docker-compose.yml
    kompose.version: 1.30.0 (9d8dcb518)
  creationTimestamp: null
  labels:
    io.kompose.service: worker
  name: worker
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: worker
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: C:\Users\Han\AppData\Local\Microsoft\WinGet\Links\kompose.exe convert -f docker-compose.yml
        kompose.version: 1.30.0 (9d8dcb518)
      creationTimestamp: null
      labels:
        io.kompose.network/klass-mynetwork: "true"
        io.kompose.service: worker
    spec:
      containers:
        - args:
            - sh
            - -c
            - |2-
               if ! getent group 2222 > /dev/null 2>&1; then
                groupadd -g 2222 vadklass &&
                useradd -u 2222 -g 2222 -m -d /home/vadklass vadklass &&
                chown -R 2222:2222 /usr/src/app &&
                su vadklass -c "whoami && celery -A src.klass.vad_fastapi.worker.celery worker --loglevel=info --logfile=/usr/src/app/vol_mount/logs/celery_worker.log"
              else
                su vadklass -c "whoami && celery -A src.klass.vad_fastapi.worker.celery worker --loglevel=info --logfile=/usr/src/app/vol_mount/logs/celery_worker.log"
              fi
          env:
            - name: CELERY_BROKER_URL
              value: amqp://admin:mypass@rabbit:5672
            - name: CELERY_RESULT_BACKEND
              value: redis://redis:6379/0
            - name: CELERY_TASK_TRACK_STARTED
              value: "true"
          image: vad_deploy:0.1.2
          name: worker
          resources: {}
          volumeMounts:
            - mountPath: /usr/src/app/vol_mount
              name: worker-claim0
      restartPolicy: Always
      volumes:
        - name: worker-claim0
          persistentVolumeClaim:
            claimName: worker-claim0
status: {}
