version: 1

disable_existing_loggers: False

formatters:
  simple:
    format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  json:
    format: "%(asctime)s %(process)d %(name)s %(levelname)s %(message)s"
    class: pythonjsonlogger.jsonlogger.JsonFormatter
    datefmt: "%Y-%m-%dT%H:%M:%S%z"

handlers:
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: json  # simple
    stream: ext://sys.stdout

  info_file_handler:
    class: logging.handlers.RotatingFileHandler
    level: INFO
    formatter: json  # simple
    filename: info.log
    maxBytes: 10485760 # 10MB
    backupCount: 20
    encoding: utf8
    delay: True

  rich:
    class: kedro.logging.RichHandler
    rich_tracebacks: True
    # Advance options for customisation.
    # See https://docs.kedro.org/en/stable/logging/logging.html#project-side-logging-configuration
    # tracebacks_show_locals: False

loggers:
  kedro:
    level: INFO

  klass:
    level: INFO

root:
  level: INFO
  handlers: [rich, console, info_file_handler]
